### ISSUE TITLE
Cannot display the graph

### ISSUE THREAD

**Issue by DonTortuga** [highchartTable/jquery-highchartTable-plugin#10]
Hi,

Everytime I try to display the graph using the code given in the examples I get this error "Uncaught graph-container is not available in this DOM or available multiple times". I feel dummy but I figure out where the problem come from.

**Comment by maricar1** [comment]
Hello there! How is the error fixed? I have the same error, I cannot figure what will be the solution

**Comment by maricar1** [comment]
![image](https://user-images.githubusercontent.com/45760284/49736748-e6753d00-fcc5-11e8-948e-c0d963233c45.png)
This is my error.
