### ISSUE TITLE
data-graph-yaxis-max

### ISSUE THREAD

**Issue by andriuhatm** [highchartTable/jquery-highchartTable-plugin#72]
Is there something for y-axis max value?

**Comment by Guppy49** [comment]
Yes, and several others following the same principle:
data-graph-yaxis-1-min=
data-graph-yaxis-1-max=
data-graph-yaxis-1-tick-interval=
data-graph-yaxis-1-title-text=

**Comment by andriuhatm** [comment]
i tried data-graph-yaxis-1-max="10" and data-graph-yaxis-max="10" ...
Didn't work.

**Comment by Guppy49** [comment]
I found a random jsfiddle http://jsfiddle.net/Js8Wj/
Try adding data-graph-yaxis-1-max="8000"
And you will see it works here.
So there is another issue in your code.

**Comment by andriuhatm** [comment]
yes thx, it should work..
but, http://jsfiddle.net/andriuhatm/eesns9mh/

**Comment by Guppy49** [comment]
It seems that it doesn't work with JQuery 2.
I tried changing to JQuery 1.11.0 and then it works

**Comment by andriuhatm** [comment]
Thanks for help..
