### ISSUE TITLE
redraw chart when table td changes?

### ISSUE THREAD

**Issue by gstoa** [highchartTable/jquery-highchartTable-plugin#84]
After drawing a chart based on a table, I am updating the td values with an ajax call.  How to refresh/redraw the current chart with these new table values?

**Comment by ratibus** [comment]
Hi. First, thanks for using our lib :)

You need to fetch your table with jQuery and call the highchartTable() method.

For example, if your table can be identified by the id #myTable:
```js
$('#myTable').highchartTable();
```

Tell me if it suits your needs.

**Comment by gstoa** [comment]
Well that couldn't have been any easier - thanks!  I was initially thinking that there might be a draw event or similar which automatically changes the chart based on the td table values changing.  I can live with redrawing the whole chart, no problem.

**Comment by ratibus** [comment]
Cool :+1: Allow me to close this issue then ;)
